"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TComplexity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIFFORD_FIELD_NUMBER: builtins.int
    ROTATIONS_FIELD_NUMBER: builtins.int
    T_FIELD_NUMBER: builtins.int
    clifford: builtins.int
    rotations: builtins.int
    t: builtins.int
    def __init__(
        self,
        *,
        clifford: builtins.int = ...,
        rotations: builtins.int = ...,
        t: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["clifford", b"clifford", "rotations", b"rotations", "t", b"t"]) -> None: ...

global___TComplexity = TComplexity
