# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/api/annotations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qualtran.api import args_pb2 as qualtran_dot_api_dot_args__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1equaltran/api/annotations.proto\x12\x08qualtran\x1a\x17qualtran/api/args.proto\"=\n\x0bTComplexity\x12\x10\n\x08\x63lifford\x18\x01 \x01(\x03\x12\x11\n\trotations\x18\x02 \x01(\x03\x12\t\n\x01t\x18\x03 \x01(\x03\"\x90\x01\n\nBloqCounts\x12\x39\n\x0b\x62loq_counts\x18\x01 \x03(\x0b\x32$.qualtran.BloqCounts.BloqCountsEntry\x1aG\n\x0f\x42loqCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.qualtran.IntOrSympy:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.api.annotations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _BLOQCOUNTS_BLOQCOUNTSENTRY._options = None
    _BLOQCOUNTS_BLOQCOUNTSENTRY._serialized_options = b'8\001'
    _globals['_TCOMPLEXITY']._serialized_start = 69
    _globals['_TCOMPLEXITY']._serialized_end = 130
    _globals['_BLOQCOUNTS']._serialized_start = 133
    _globals['_BLOQCOUNTS']._serialized_end = 277
    _globals['_BLOQCOUNTS_BLOQCOUNTSENTRY']._serialized_start = 206
    _globals['_BLOQCOUNTS_BLOQCOUNTSENTRY']._serialized_end = 277
# @@protoc_insertion_point(module_scope)
