"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class IntOrSympy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT_VAL_FIELD_NUMBER: builtins.int
    SYMPY_EXPR_FIELD_NUMBER: builtins.int
    int_val: builtins.int
    sympy_expr: builtins.str
    def __init__(
        self,
        *,
        int_val: builtins.int = ...,
        sympy_expr: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["int_val", b"int_val", "sympy_expr", b"sympy_expr", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["int_val", b"int_val", "sympy_expr", b"sympy_expr", "val", b"val"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["val", b"val"]) -> typing_extensions.Literal["int_val", "sympy_expr"] | None: ...

global___IntOrSympy = IntOrSympy

@typing_extensions.final
class NDArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAPE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """A flattened numpy array. Let `a` be a numpy array. It should be serialized / deserialized as:
        >>> shape, dtype, data = a.shape, a.dtype, a.tobytes()
        >>> arr = np.ndarray(shape, dtype, data)
        """
    dtype: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        dtype: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "dtype", b"dtype", "shape", b"shape"]) -> None: ...

global___NDArray = NDArray

@typing_extensions.final
class BloqArg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    INT_VAL_FIELD_NUMBER: builtins.int
    FLOAT_VAL_FIELD_NUMBER: builtins.int
    STRING_VAL_FIELD_NUMBER: builtins.int
    SYMPY_EXPR_FIELD_NUMBER: builtins.int
    NDARRAY_FIELD_NUMBER: builtins.int
    SUBBLOQ_FIELD_NUMBER: builtins.int
    CIRQ_JSON_GZIP_FIELD_NUMBER: builtins.int
    name: builtins.str
    int_val: builtins.int
    float_val: builtins.float
    string_val: builtins.str
    sympy_expr: builtins.str
    """Sympy expression generated using str(expr)."""
    @property
    def ndarray(self) -> global___NDArray:
        """N-dimensional numpy array stored as bytes."""
    subbloq: builtins.int
    """Integer reference of a subbloq. Assumes access to a BloqLibrary."""
    cirq_json_gzip: builtins.bytes
    """Gzipped JSON corresponding to a Cirq object."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        int_val: builtins.int = ...,
        float_val: builtins.float = ...,
        string_val: builtins.str = ...,
        sympy_expr: builtins.str = ...,
        ndarray: global___NDArray | None = ...,
        subbloq: builtins.int = ...,
        cirq_json_gzip: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cirq_json_gzip", b"cirq_json_gzip", "float_val", b"float_val", "int_val", b"int_val", "ndarray", b"ndarray", "string_val", b"string_val", "subbloq", b"subbloq", "sympy_expr", b"sympy_expr", "val", b"val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cirq_json_gzip", b"cirq_json_gzip", "float_val", b"float_val", "int_val", b"int_val", "name", b"name", "ndarray", b"ndarray", "string_val", b"string_val", "subbloq", b"subbloq", "sympy_expr", b"sympy_expr", "val", b"val"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["val", b"val"]) -> typing_extensions.Literal["int_val", "float_val", "string_val", "sympy_expr", "ndarray", "subbloq", "cirq_json_gzip"] | None: ...

global___BloqArg = BloqArg
