# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/api/bloq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qualtran.api import annotations_pb2 as qualtran_dot_api_dot_annotations__pb2
from qualtran.api import args_pb2 as qualtran_dot_api_dot_args__pb2
from qualtran.api import registers_pb2 as qualtran_dot_api_dot_registers__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17qualtran/api/bloq.proto\x12\x08qualtran\x1a\x1equaltran/api/annotations.proto\x1a\x17qualtran/api/args.proto\x1a\x1cqualtran/api/registers.proto\"\x8a\x01\n\x04\x42loq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x11.qualtran.BloqArg\x12&\n\tregisters\x18\x03 \x01(\x0b\x32\x13.qualtran.Registers\x12+\n\x0ct_complexity\x18\x04 \x01(\x0b\x32\x15.qualtran.TComplexity\"\xb7\x01\n\rCompositeBloq\x12\"\n\x05table\x18\x01 \x01(\x0b\x32\x13.qualtran.BloqTable\x12*\n\x05\x63\x62loq\x18\x02 \x01(\x0b\x32\x1b.qualtran.CompositeBloqLite\x12+\n\x0ct_complexity\x18\x03 \x01(\x0b\x32\x15.qualtran.TComplexity\x12)\n\x0b\x62loq_counts\x18\x04 \x01(\x0b\x32\x14.qualtran.BloqCounts\"+\n\x0c\x42loqInstance\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62loq_id\x18\x02 \x01(\x05\"\x8d\x01\n\x06Soquet\x12/\n\rbloq_instance\x18\x01 \x01(\x0b\x32\x16.qualtran.BloqInstanceH\x00\x12\x14\n\ndangling_t\x18\x02 \x01(\tH\x00\x12$\n\x08register\x18\x03 \x01(\x0b\x32\x12.qualtran.Register\x12\r\n\x05index\x18\x04 \x03(\x05\x42\x07\n\x05\x62inst\"M\n\nConnection\x12\x1e\n\x04left\x18\x01 \x01(\x0b\x32\x10.qualtran.Soquet\x12\x1f\n\x05right\x18\x02 \x01(\x0b\x32\x10.qualtran.Soquet\"t\n\x11\x43ompositeBloqLite\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\tregisters\x18\x02 \x01(\x0b\x32\x13.qualtran.Registers\x12)\n\x0b\x63onnections\x18\x03 \x03(\x0b\x32\x14.qualtran.Connection\"l\n\x0b\x42loqOrCbloq\x12\x1e\n\x04\x62loq\x18\x01 \x01(\x0b\x32\x0e.qualtran.BloqH\x00\x12,\n\x05\x63\x62loq\x18\x02 \x01(\x0b\x32\x1b.qualtran.CompositeBloqLiteH\x00\x42\x0f\n\rbloq_or_cbloq\"1\n\tBloqTable\x12$\n\x05\x62loqs\x18\x01 \x03(\x0b\x32\x15.qualtran.BloqOrCbloqb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.api.bloq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals['_BLOQ']._serialized_start = 125
    _globals['_BLOQ']._serialized_end = 263
    _globals['_COMPOSITEBLOQ']._serialized_start = 266
    _globals['_COMPOSITEBLOQ']._serialized_end = 449
    _globals['_BLOQINSTANCE']._serialized_start = 451
    _globals['_BLOQINSTANCE']._serialized_end = 494
    _globals['_SOQUET']._serialized_start = 497
    _globals['_SOQUET']._serialized_end = 638
    _globals['_CONNECTION']._serialized_start = 640
    _globals['_CONNECTION']._serialized_end = 717
    _globals['_COMPOSITEBLOQLITE']._serialized_start = 719
    _globals['_COMPOSITEBLOQLITE']._serialized_end = 835
    _globals['_BLOQORCBLOQ']._serialized_start = 837
    _globals['_BLOQORCBLOQ']._serialized_end = 945
    _globals['_BLOQTABLE']._serialized_start = 947
    _globals['_BLOQTABLE']._serialized_end = 996
# @@protoc_insertion_point(module_scope)
