"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Register(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Side:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Register._Side.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Register._Side.ValueType  # 0
        LEFT: Register._Side.ValueType  # 1
        RIGHT: Register._Side.ValueType  # 2
        THRU: Register._Side.ValueType  # 3

    class Side(_Side, metaclass=_SideEnumTypeWrapper):
        """A quantum register."""

    UNKNOWN: Register.Side.ValueType  # 0
    LEFT: Register.Side.ValueType  # 1
    RIGHT: Register.Side.ValueType  # 2
    THRU: Register.Side.ValueType  # 3

    NAME_FIELD_NUMBER: builtins.int
    BITSIZE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    name: builtins.str
    bitsize: builtins.int
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    side: global___Register.Side.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        bitsize: builtins.int = ...,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        side: global___Register.Side.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bitsize", b"bitsize", "name", b"name", "shape", b"shape", "side", b"side"]) -> None: ...

global___Register = Register

@typing_extensions.final
class Registers(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGISTERS_FIELD_NUMBER: builtins.int
    @property
    def registers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Register]:
        """A collection of Registers."""
    def __init__(
        self,
        *,
        registers: collections.abc.Iterable[global___Register] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["registers", b"registers"]) -> None: ...

global___Registers = Registers
