#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Autogenerates the notebooks and reports whether there were any changes.
#
# Usage:
#     check/autogenerate-notebooks
#
################################################################################

python dev_tools/autogenerate-bloqs-notebooks-v2.py || exit $?

if output=$(git status --porcelain) && [ -z "$output" ]; then
  # Working directory clean
  exit 0
else
  # Uncommitted changes
  echo "$output"
  exit 1
fi
