#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
# Runs mypy on the repository using a preconfigured mypy.ini file.
#
# Usage:
#     check/mypy [--flags]
################################################################################

# Get the working directory to the repo root.
thisdir="$(dirname "${BASH_SOURCE[0]}")" || exit $?
topdir="$(git -C "${thisdir}" rev-parse --show-toplevel)" || exit $?
cd "${topdir}" || exit $?

CONFIG_FILE='mypy.ini'

# Mypy 2.0 added a `-n` flag for parallel workers. Use it if possible.
# shellcheck disable=SC2207  # Need the next command *not* to be quoted.
mypy_version_array=( $(mypy --version) )
mypy_major_version="${mypy_version_array[1]%%.*}"
n_workers=()
if (( mypy_major_version >= 2 )); then
    # Mypy 2.x doesn't support a value of 'auto' like pytest does. We have to
    # come up with a number. This uses (#cpus - 1) or 16, whichever is smallest.
    num_workers=$(python -c 'import os; c = os.cpu_count() or 1; print(min(16, max(1, c - 1)))')
    n_workers=("-n" "${num_workers}")
fi

echo -e -n "\033[31m"
mypy --config-file=dev_tools/conf/$CONFIG_FILE "${n_workers[@]}" "$@" qualtran/
result=$?
echo -e -n "\033[0m"

exit ${result}
