#!/usr/bin/env bash

################################################################################
# Runs pylint on the repository using a preconfigured .pylintrc file.
#
# Usage:
#     check/pylint [--flags for pylint]
################################################################################

# Get the working directory to the repo root.
thisdir="$(dirname "${BASH_SOURCE[0]}")" || exit $?
topdir="$(git -C "${thisdir}" rev-parse --show-toplevel)" || exit $?
cd "${topdir}" || exit $?

# Add dev_tools to $PYTHONPATH so that pylint can find custom checkers
PYTHONPATH=dev_tools:dev_tools/qualtran_dev_tools pylint --jobs=0 --rcfile=dev_tools/conf/.pylintrc "$@" qualtran/ dev_tools/
