#!/usr/bin/env bash

# Get the working directory to the repo root.
cd "$( dirname "${BASH_SOURCE[0]}" )" || exit 1
cd "$(git rev-parse --show-toplevel)" || exit 1

# Run in parallel by default.  Pass the `-n0` option for a single-process run.
# (the last `-n` option wins)
PYTEST_ARGS=( "-n=auto" "-m" 'not slow and not notebook' "$@" )
pytest "${PYTEST_ARGS[@]}" qualtran/
RESULT=$?

exit "$RESULT"
