#!/usr/bin/env bash

################################################################################
# Runs the full pytest suite on the repository.
#
# Usage:
#     check/pytest-full [--flags for pytest]
#
################################################################################

# Get the working directory to the repo root.
cd "$( dirname "${BASH_SOURCE[0]}" )" || exit 1
cd "$(git rev-parse --show-toplevel)" || exit 1

# Run in parallel by default.  Pass the `-n0` option for a single-process run.
# (the last `-n` option wins)
PYTEST_ARGS=( "-n=auto" "$@" )

pytest "${PYTEST_ARGS[@]}" qualtran/
RESULT=$?

exit "$RESULT"
