# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/annotations.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!qualtran/protos/annotations.proto\x12\x08qualtran\"=\n\x0bTComplexity\x12\x10\n\x08\x63lifford\x18\x01 \x01(\x03\x12\x11\n\trotations\x18\x02 \x01(\x03\x12\t\n\x01t\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.annotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TCOMPLEXITY']._serialized_start=47
  _globals['_TCOMPLEXITY']._serialized_end=108
# @@protoc_insertion_point(module_scope)
