"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class IntOrSympy(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INT_VAL_FIELD_NUMBER: _builtins.int
    SYMPY_EXPR_FIELD_NUMBER: _builtins.int
    int_val: _builtins.int
    sympy_expr: _builtins.str
    def __init__(
        self,
        *,
        int_val: _builtins.int = ...,
        sympy_expr: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["int_val", b"int_val", "sympy_expr", b"sympy_expr", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["int_val", b"int_val", "sympy_expr", b"sympy_expr", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_val: _TypeAlias = _typing.Literal["int_val", "sympy_expr"]  # noqa: Y015
    _WhichOneofArgType_val: _TypeAlias = _typing.Literal["val", b"val"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_val) -> _WhichOneofReturnType_val | None: ...

Global___IntOrSympy: _TypeAlias = IntOrSympy  # noqa: Y015

@_typing.final
class NDArray(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NDARRAY_FIELD_NUMBER: _builtins.int
    ndarray: _builtins.bytes
    """A Numpy array serialized as bytes using np.save() / np.load()."""
    def __init__(
        self,
        *,
        ndarray: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ndarray", b"ndarray"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NDArray: _TypeAlias = NDArray  # noqa: Y015

@_typing.final
class Complex(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REAL_FIELD_NUMBER: _builtins.int
    IMAG_FIELD_NUMBER: _builtins.int
    real: _builtins.float
    imag: _builtins.float
    def __init__(
        self,
        *,
        real: _builtins.float = ...,
        imag: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["imag", b"imag", "real", b"real"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Complex: _TypeAlias = Complex  # noqa: Y015
