# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/args.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aqualtran/protos/args.proto\x12\x08qualtran\"<\n\nIntOrSympy\x12\x11\n\x07int_val\x18\x01 \x01(\x03H\x00\x12\x14\n\nsympy_expr\x18\x02 \x01(\tH\x00\x42\x05\n\x03val\"\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.args_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTORSYMPY']._serialized_start=40
  _globals['_INTORSYMPY']._serialized_end=100
  _globals['_NDARRAY']._serialized_start=102
  _globals['_NDARRAY']._serialized_end=128
# @@protoc_insertion_point(module_scope)
