"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from qualtran.protos import annotations_pb2 as _annotations_pb2
from qualtran.protos import args_pb2 as _args_pb2
from qualtran.protos import ctrl_spec_pb2 as _ctrl_spec_pb2
from qualtran.protos import data_types_pb2 as _data_types_pb2
from qualtran.protos import ec_point_pb2 as _ec_point_pb2
from qualtran.protos import registers_pb2 as _registers_pb2
from qualtran.protos import sympy_pb2 as _sympy_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BloqArg(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    INT_VAL_FIELD_NUMBER: _builtins.int
    FLOAT_VAL_FIELD_NUMBER: _builtins.int
    STRING_VAL_FIELD_NUMBER: _builtins.int
    SYMPY_EXPR_FIELD_NUMBER: _builtins.int
    NDARRAY_FIELD_NUMBER: _builtins.int
    SUBBLOQ_FIELD_NUMBER: _builtins.int
    CIRQ_JSON_GZIP_FIELD_NUMBER: _builtins.int
    QDATA_TYPE_FIELD_NUMBER: _builtins.int
    REGISTER_FIELD_NUMBER: _builtins.int
    REGISTERS_FIELD_NUMBER: _builtins.int
    CTRL_SPEC_FIELD_NUMBER: _builtins.int
    COMPLEX_VAL_FIELD_NUMBER: _builtins.int
    EC_POINT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    int_val: _builtins.int
    float_val: _builtins.float
    string_val: _builtins.str
    subbloq: _builtins.int
    """Integer reference of a subbloq. Assumes access to a BloqLibrary."""
    cirq_json_gzip: _builtins.bytes
    """Gzipped JSON corresponding to a Cirq object."""
    @_builtins.property
    def sympy_expr(self) -> _sympy_pb2.Term:
        """Sympy expression generated using str(expr)."""

    @_builtins.property
    def ndarray(self) -> _args_pb2.NDArray:
        """N-dimensional numpy array stored as bytes."""

    @_builtins.property
    def qdata_type(self) -> _data_types_pb2.QDataType:
        """data type"""

    @_builtins.property
    def register(self) -> _registers_pb2.Register:
        """A Register object, accepted as an argument."""

    @_builtins.property
    def registers(self) -> _registers_pb2.Registers:
        """A repeated list of one or more registers, accepted as arguments."""

    @_builtins.property
    def ctrl_spec(self) -> _ctrl_spec_pb2.CtrlSpec:
        """Ctrl Spec for controlled bloqs"""

    @_builtins.property
    def complex_val(self) -> _args_pb2.Complex: ...
    @_builtins.property
    def ec_point(self) -> _ec_point_pb2.ECPoint:
        """An elliptical curve point for ECC bloqs"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        int_val: _builtins.int = ...,
        float_val: _builtins.float = ...,
        string_val: _builtins.str = ...,
        sympy_expr: _sympy_pb2.Term | None = ...,
        ndarray: _args_pb2.NDArray | None = ...,
        subbloq: _builtins.int = ...,
        cirq_json_gzip: _builtins.bytes = ...,
        qdata_type: _data_types_pb2.QDataType | None = ...,
        register: _registers_pb2.Register | None = ...,
        registers: _registers_pb2.Registers | None = ...,
        ctrl_spec: _ctrl_spec_pb2.CtrlSpec | None = ...,
        complex_val: _args_pb2.Complex | None = ...,
        ec_point: _ec_point_pb2.ECPoint | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cirq_json_gzip", b"cirq_json_gzip", "complex_val", b"complex_val", "ctrl_spec", b"ctrl_spec", "ec_point", b"ec_point", "float_val", b"float_val", "int_val", b"int_val", "ndarray", b"ndarray", "qdata_type", b"qdata_type", "register", b"register", "registers", b"registers", "string_val", b"string_val", "subbloq", b"subbloq", "sympy_expr", b"sympy_expr", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cirq_json_gzip", b"cirq_json_gzip", "complex_val", b"complex_val", "ctrl_spec", b"ctrl_spec", "ec_point", b"ec_point", "float_val", b"float_val", "int_val", b"int_val", "name", b"name", "ndarray", b"ndarray", "qdata_type", b"qdata_type", "register", b"register", "registers", b"registers", "string_val", b"string_val", "subbloq", b"subbloq", "sympy_expr", b"sympy_expr", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_val: _TypeAlias = _typing.Literal["int_val", "float_val", "string_val", "sympy_expr", "ndarray", "subbloq", "cirq_json_gzip", "qdata_type", "register", "registers", "ctrl_spec", "complex_val", "ec_point"]  # noqa: Y015
    _WhichOneofArgType_val: _TypeAlias = _typing.Literal["val", b"val"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_val) -> _WhichOneofReturnType_val | None: ...

Global___BloqArg: _TypeAlias = BloqArg  # noqa: Y015

@_typing.final
class BloqLibrary(_message.Message):
    """A library of Bloqs. BloqLibrary should be used to represent both primitive Bloqs and
    composite Bloqs; i.e. Bloqs consisting of other subbloqs, like `CompositeBloq`,
    `ControlledBloq` etc.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class BloqWithDecomposition(_message.Message):
        """Decompositions are specified using integer IDs referencing other Bloqs within this library."""

        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class BloqCountsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> _args_pb2.IntOrSympy: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: _args_pb2.IntOrSympy | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        BLOQ_ID_FIELD_NUMBER: _builtins.int
        DECOMPOSITION_FIELD_NUMBER: _builtins.int
        BLOQ_COUNTS_FIELD_NUMBER: _builtins.int
        BLOQ_FIELD_NUMBER: _builtins.int
        bloq_id: _builtins.int
        """Unique identifier for this Bloq within the library."""
        @_builtins.property
        def decomposition(self) -> _containers.RepeatedCompositeFieldContainer[Global___Connection]:
            """Decomposition of the Bloq as an edge-list."""

        @_builtins.property
        def bloq_counts(self) -> _containers.MessageMap[_builtins.int, _args_pb2.IntOrSympy]:
            """Rough decomposition of the Bloq as bloq-counts."""

        @_builtins.property
        def bloq(self) -> Global___Bloq:
            """The Bloq itself."""

        def __init__(
            self,
            *,
            bloq_id: _builtins.int = ...,
            decomposition: _abc.Iterable[Global___Connection] | None = ...,
            bloq_counts: _abc.Mapping[_builtins.int, _args_pb2.IntOrSympy] | None = ...,
            bloq: Global___Bloq | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bloq", b"bloq"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bloq", b"bloq", "bloq_counts", b"bloq_counts", "bloq_id", b"bloq_id", "decomposition", b"decomposition"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    TABLE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """A name for the library."""
    @_builtins.property
    def table(self) -> _containers.RepeatedCompositeFieldContainer[Global___BloqLibrary.BloqWithDecomposition]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        table: _abc.Iterable[Global___BloqLibrary.BloqWithDecomposition] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "table", b"table"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BloqLibrary: _TypeAlias = BloqLibrary  # noqa: Y015

@_typing.final
class Bloq(_message.Message):
    """Messages to enable efficient description of a BloqLibrary, including Bloq decompositions in
    terms of other simpler bloqs.

    A Bloq without it's decomposition.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ARGS_FIELD_NUMBER: _builtins.int
    REGISTERS_FIELD_NUMBER: _builtins.int
    T_COMPLEXITY_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """`name` identifies the Bloq."""
    @_builtins.property
    def args(self) -> _containers.RepeatedCompositeFieldContainer[Global___BloqArg]:
        """`Args` are used to construct the Bloq."""

    @_builtins.property
    def registers(self) -> _registers_pb2.Registers:
        """`Registers` specify the signature of the Bloq and are often derived using `args`."""

    @_builtins.property
    def t_complexity(self) -> _annotations_pb2.TComplexity:
        """Other useful annotations."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        args: _abc.Iterable[Global___BloqArg] | None = ...,
        registers: _registers_pb2.Registers | None = ...,
        t_complexity: _annotations_pb2.TComplexity | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["registers", b"registers", "t_complexity", b"t_complexity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["args", b"args", "name", b"name", "registers", b"registers", "t_complexity", b"t_complexity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Bloq: _TypeAlias = Bloq  # noqa: Y015

@_typing.final
class BloqInstance(_message.Message):
    """Specific instance of a Bloq."""

    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    BLOQ_ID_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.int
    bloq_id: _builtins.int
    def __init__(
        self,
        *,
        instance_id: _builtins.int = ...,
        bloq_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bloq_id", b"bloq_id", "instance_id", b"instance_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BloqInstance: _TypeAlias = BloqInstance  # noqa: Y015

@_typing.final
class Soquet(_message.Message):
    """One half of a connection."""

    DESCRIPTOR: _descriptor.Descriptor

    BLOQ_INSTANCE_FIELD_NUMBER: _builtins.int
    DANGLING_T_FIELD_NUMBER: _builtins.int
    REGISTER_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    dangling_t: _builtins.str
    @_builtins.property
    def bloq_instance(self) -> Global___BloqInstance: ...
    @_builtins.property
    def register(self) -> _registers_pb2.Register: ...
    @_builtins.property
    def index(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        bloq_instance: Global___BloqInstance | None = ...,
        dangling_t: _builtins.str = ...,
        register: _registers_pb2.Register | None = ...,
        index: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["binst", b"binst", "bloq_instance", b"bloq_instance", "dangling_t", b"dangling_t", "register", b"register"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binst", b"binst", "bloq_instance", b"bloq_instance", "dangling_t", b"dangling_t", "index", b"index", "register", b"register"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_binst: _TypeAlias = _typing.Literal["bloq_instance", "dangling_t"]  # noqa: Y015
    _WhichOneofArgType_binst: _TypeAlias = _typing.Literal["binst", b"binst"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_binst) -> _WhichOneofReturnType_binst | None: ...

Global___Soquet: _TypeAlias = Soquet  # noqa: Y015

@_typing.final
class Connection(_message.Message):
    """A connection between two Soquets. Quantum compute graph can be represented as a list of
    connections.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LEFT_FIELD_NUMBER: _builtins.int
    RIGHT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def left(self) -> Global___Soquet: ...
    @_builtins.property
    def right(self) -> Global___Soquet: ...
    def __init__(
        self,
        *,
        left: Global___Soquet | None = ...,
        right: Global___Soquet | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["left", b"left", "right", b"right"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["left", b"left", "right", b"right"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Connection: _TypeAlias = Connection  # noqa: Y015
