# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/ctrl_spec.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qualtran.protos import data_types_pb2 as qualtran_dot_protos_dot_data__types__pb2
from qualtran.protos import args_pb2 as qualtran_dot_protos_dot_args__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fqualtran/protos/ctrl_spec.proto\x12\x08qualtran\x1a qualtran/protos/data_types.proto\x1a\x1aqualtran/protos/args.proto\"P\n\x08\x43trlSpec\x12$\n\x07qdtypes\x18\x01 \x03(\x0b\x32\x13.qualtran.QDataType\x12\x1e\n\x03\x63vs\x18\x02 \x03(\x0b\x32\x11.qualtran.NDArrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.ctrl_spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CTRLSPEC']._serialized_start=107
  _globals['_CTRLSPEC']._serialized_end=187
# @@protoc_insertion_point(module_scope)
