"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import qualtran.protos.args_pb2
import qualtran.protos.data_types_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CtrlSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QDTYPES_FIELD_NUMBER: builtins.int
    CVS_FIELD_NUMBER: builtins.int
    @property
    def qdtypes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[qualtran.protos.data_types_pb2.QDataType]: ...
    @property
    def cvs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[qualtran.protos.args_pb2.NDArray]: ...
    def __init__(
        self,
        *,
        qdtypes: collections.abc.Iterable[qualtran.protos.data_types_pb2.QDataType] | None = ...,
        cvs: collections.abc.Iterable[qualtran.protos.args_pb2.NDArray] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cvs", b"cvs", "qdtypes", b"qdtypes"]) -> None: ...

global___CtrlSpec = CtrlSpec
