"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from qualtran.protos import args_pb2 as _args_pb2
from qualtran.protos import data_types_pb2 as _data_types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CtrlSpec(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QDTYPES_FIELD_NUMBER: _builtins.int
    CVS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def qdtypes(self) -> _containers.RepeatedCompositeFieldContainer[_data_types_pb2.QDataType]: ...
    @_builtins.property
    def cvs(self) -> _containers.RepeatedCompositeFieldContainer[_args_pb2.NDArray]: ...
    def __init__(
        self,
        *,
        qdtypes: _abc.Iterable[_data_types_pb2.QDataType] | None = ...,
        cvs: _abc.Iterable[_args_pb2.NDArray] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cvs", b"cvs", "qdtypes", b"qdtypes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CtrlSpec: _TypeAlias = CtrlSpec  # noqa: Y015
