"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from qualtran.protos import args_pb2 as _args_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QBit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QBit: _TypeAlias = QBit  # noqa: Y015

@_typing.final
class QAny(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...

Global___QAny: _TypeAlias = QAny  # noqa: Y015

@_typing.final
class QInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...

Global___QInt: _TypeAlias = QInt  # noqa: Y015

@_typing.final
class QIntOnesComp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...

Global___QIntOnesComp: _TypeAlias = QIntOnesComp  # noqa: Y015

@_typing.final
class QUInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...

Global___QUInt: _TypeAlias = QUInt  # noqa: Y015

@_typing.final
class QMontgomeryUInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "bitsize", b"bitsize"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...

Global___QMontgomeryUInt: _TypeAlias = QMontgomeryUInt  # noqa: Y015

@_typing.final
class BQUInt(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    ITERATION_LENGTH_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    @_builtins.property
    def iteration_length(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
        iteration_length: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "_iteration_length", b"_iteration_length", "bitsize", b"bitsize", "iteration_length", b"iteration_length"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "_iteration_length", b"_iteration_length", "bitsize", b"bitsize", "iteration_length", b"iteration_length"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    _WhichOneofReturnType__iteration_length: _TypeAlias = _typing.Literal["iteration_length"]  # noqa: Y015
    _WhichOneofArgType__iteration_length: _TypeAlias = _typing.Literal["_iteration_length", b"_iteration_length"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__iteration_length) -> _WhichOneofReturnType__iteration_length | None: ...

Global___BQUInt: _TypeAlias = BQUInt  # noqa: Y015

@_typing.final
class QFxp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BITSIZE_FIELD_NUMBER: _builtins.int
    NUM_FRAC_FIELD_NUMBER: _builtins.int
    SIGNED_FIELD_NUMBER: _builtins.int
    signed: _builtins.bool
    @_builtins.property
    def bitsize(self) -> _args_pb2.IntOrSympy: ...
    @_builtins.property
    def num_frac(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        bitsize: _args_pb2.IntOrSympy | None = ...,
        num_frac: _args_pb2.IntOrSympy | None = ...,
        signed: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "_num_frac", b"_num_frac", "_signed", b"_signed", "bitsize", b"bitsize", "num_frac", b"num_frac", "signed", b"signed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize", "_num_frac", b"_num_frac", "_signed", b"_signed", "bitsize", b"bitsize", "num_frac", b"num_frac", "signed", b"signed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bitsize: _TypeAlias = _typing.Literal["bitsize"]  # noqa: Y015
    _WhichOneofArgType__bitsize: _TypeAlias = _typing.Literal["_bitsize", b"_bitsize"]  # noqa: Y015
    _WhichOneofReturnType__num_frac: _TypeAlias = _typing.Literal["num_frac"]  # noqa: Y015
    _WhichOneofArgType__num_frac: _TypeAlias = _typing.Literal["_num_frac", b"_num_frac"]  # noqa: Y015
    _WhichOneofReturnType__signed: _TypeAlias = _typing.Literal["signed"]  # noqa: Y015
    _WhichOneofArgType__signed: _TypeAlias = _typing.Literal["_signed", b"_signed"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bitsize) -> _WhichOneofReturnType__bitsize | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__num_frac) -> _WhichOneofReturnType__num_frac | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__signed) -> _WhichOneofReturnType__signed | None: ...

Global___QFxp: _TypeAlias = QFxp  # noqa: Y015

@_typing.final
class QDataType(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    QBIT_FIELD_NUMBER: _builtins.int
    QANY_FIELD_NUMBER: _builtins.int
    QINT_FIELD_NUMBER: _builtins.int
    QINT_ONES_COMP_FIELD_NUMBER: _builtins.int
    QUINT_FIELD_NUMBER: _builtins.int
    BQUINT_FIELD_NUMBER: _builtins.int
    QFXP_FIELD_NUMBER: _builtins.int
    QMONTGOMERY_UINT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def qbit(self) -> Global___QBit: ...
    @_builtins.property
    def qany(self) -> Global___QAny: ...
    @_builtins.property
    def qint(self) -> Global___QInt: ...
    @_builtins.property
    def qint_ones_comp(self) -> Global___QIntOnesComp: ...
    @_builtins.property
    def quint(self) -> Global___QUInt: ...
    @_builtins.property
    def bquint(self) -> Global___BQUInt: ...
    @_builtins.property
    def qfxp(self) -> Global___QFxp: ...
    @_builtins.property
    def qmontgomery_uint(self) -> Global___QMontgomeryUInt: ...
    def __init__(
        self,
        *,
        qbit: Global___QBit | None = ...,
        qany: Global___QAny | None = ...,
        qint: Global___QInt | None = ...,
        qint_ones_comp: Global___QIntOnesComp | None = ...,
        quint: Global___QUInt | None = ...,
        bquint: Global___BQUInt | None = ...,
        qfxp: Global___QFxp | None = ...,
        qmontgomery_uint: Global___QMontgomeryUInt | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bquint", b"bquint", "qany", b"qany", "qbit", b"qbit", "qfxp", b"qfxp", "qint", b"qint", "qint_ones_comp", b"qint_ones_comp", "qmontgomery_uint", b"qmontgomery_uint", "quint", b"quint", "val", b"val"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bquint", b"bquint", "qany", b"qany", "qbit", b"qbit", "qfxp", b"qfxp", "qint", b"qint", "qint_ones_comp", b"qint_ones_comp", "qmontgomery_uint", b"qmontgomery_uint", "quint", b"quint", "val", b"val"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_val: _TypeAlias = _typing.Literal["qbit", "qany", "qint", "qint_ones_comp", "quint", "bquint", "qfxp", "qmontgomery_uint"]  # noqa: Y015
    _WhichOneofArgType_val: _TypeAlias = _typing.Literal["val", b"val"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_val) -> _WhichOneofReturnType_val | None: ...

Global___QDataType: _TypeAlias = QDataType  # noqa: Y015
