"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2024 Google LLC
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
https://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from qualtran.protos import args_pb2 as _args_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ECPoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    MOD_FIELD_NUMBER: _builtins.int
    CURVE_A_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def x(self) -> _args_pb2.IntOrSympy: ...
    @_builtins.property
    def y(self) -> _args_pb2.IntOrSympy: ...
    @_builtins.property
    def mod(self) -> _args_pb2.IntOrSympy: ...
    @_builtins.property
    def curve_a(self) -> _args_pb2.IntOrSympy: ...
    def __init__(
        self,
        *,
        x: _args_pb2.IntOrSympy | None = ...,
        y: _args_pb2.IntOrSympy | None = ...,
        mod: _args_pb2.IntOrSympy | None = ...,
        curve_a: _args_pb2.IntOrSympy | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_curve_a", b"_curve_a", "curve_a", b"curve_a", "mod", b"mod", "x", b"x", "y", b"y"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_curve_a", b"_curve_a", "curve_a", b"curve_a", "mod", b"mod", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__curve_a: _TypeAlias = _typing.Literal["curve_a"]  # noqa: Y015
    _WhichOneofArgType__curve_a: _TypeAlias = _typing.Literal["_curve_a", b"_curve_a"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__curve_a) -> _WhichOneofReturnType__curve_a | None: ...

Global___ECPoint: _TypeAlias = ECPoint  # noqa: Y015
