# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/ec_point.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qualtran.protos import args_pb2 as qualtran_dot_protos_dot_args__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1equaltran/protos/ec_point.proto\x12\x08qualtran\x1a\x1aqualtran/protos/args.proto\"\xa6\x01\n\x07\x45\x43Point\x12\x1f\n\x01x\x18\x01 \x01(\x0b\x32\x14.qualtran.IntOrSympy\x12\x1f\n\x01y\x18\x02 \x01(\x0b\x32\x14.qualtran.IntOrSympy\x12!\n\x03mod\x18\x03 \x01(\x0b\x32\x14.qualtran.IntOrSympy\x12*\n\x07\x63urve_a\x18\x04 \x01(\x0b\x32\x14.qualtran.IntOrSympyH\x00\x88\x01\x01\x42\n\n\x08_curve_ab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.ec_point_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ECPOINT']._serialized_start=73
  _globals['_ECPOINT']._serialized_end=239
# @@protoc_insertion_point(module_scope)
