"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from qualtran.protos import args_pb2 as _args_pb2
from qualtran.protos import data_types_pb2 as _data_types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Register(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Side:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SideEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Register._Side.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: Register._Side.ValueType  # 0
        LEFT: Register._Side.ValueType  # 1
        RIGHT: Register._Side.ValueType  # 2
        THRU: Register._Side.ValueType  # 3

    class Side(_Side, metaclass=_SideEnumTypeWrapper):
        """A quantum register."""

    UNKNOWN: Register.Side.ValueType  # 0
    LEFT: Register.Side.ValueType  # 1
    RIGHT: Register.Side.ValueType  # 2
    THRU: Register.Side.ValueType  # 3

    NAME_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    SIDE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    side: Global___Register.Side.ValueType
    @_builtins.property
    def dtype(self) -> _data_types_pb2.QDataType: ...
    @_builtins.property
    def shape(self) -> _containers.RepeatedCompositeFieldContainer[_args_pb2.IntOrSympy]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        dtype: _data_types_pb2.QDataType | None = ...,
        shape: _abc.Iterable[_args_pb2.IntOrSympy] | None = ...,
        side: Global___Register.Side.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dtype", b"dtype"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dtype", b"dtype", "name", b"name", "shape", b"shape", "side", b"side"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Register: _TypeAlias = Register  # noqa: Y015

@_typing.final
class Registers(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def registers(self) -> _containers.RepeatedCompositeFieldContainer[Global___Register]:
        """A collection of Registers."""

    def __init__(
        self,
        *,
        registers: _abc.Iterable[Global___Register] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["registers", b"registers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Registers: _TypeAlias = Registers  # noqa: Y015
