"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Function:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FunctionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Function.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NONE: _Function.ValueType  # 0
    """Each Term has an associated function. A "NONE" function means that the term
    is made up of a single parameter and can not be decomposed further.
    """
    Add: _Function.ValueType  # 1
    Mul: _Function.ValueType  # 2
    Pow: _Function.ValueType  # 3
    Mod: _Function.ValueType  # 4
    Log: _Function.ValueType  # 5
    Floor: _Function.ValueType  # 6
    Ceiling: _Function.ValueType  # 7
    Max: _Function.ValueType  # 8
    Min: _Function.ValueType  # 9
    Sin: _Function.ValueType  # 10
    Cos: _Function.ValueType  # 11
    Tan: _Function.ValueType  # 12
    Log2: _Function.ValueType  # 13

class Function(_Function, metaclass=_FunctionEnumTypeWrapper):
    """A function sympy expression."""

NONE: Function.ValueType  # 0
"""Each Term has an associated function. A "NONE" function means that the term
is made up of a single parameter and can not be decomposed further.
"""
Add: Function.ValueType  # 1
Mul: Function.ValueType  # 2
Pow: Function.ValueType  # 3
Mod: Function.ValueType  # 4
Log: Function.ValueType  # 5
Floor: Function.ValueType  # 6
Ceiling: Function.ValueType  # 7
Max: Function.ValueType  # 8
Min: Function.ValueType  # 9
Sin: Function.ValueType  # 10
Cos: Function.ValueType  # 11
Tan: Function.ValueType  # 12
Log2: Function.ValueType  # 13
Global___Function: _TypeAlias = Function  # noqa: Y015

class _ConstSymbol:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ConstSymbolEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ConstSymbol.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Pi: _ConstSymbol.ValueType  # 0
    E: _ConstSymbol.ValueType  # 1
    EulerGamma: _ConstSymbol.ValueType  # 2
    Infinity: _ConstSymbol.ValueType  # 3
    ImaginaryUnit: _ConstSymbol.ValueType  # 4

class ConstSymbol(_ConstSymbol, metaclass=_ConstSymbolEnumTypeWrapper): ...

Pi: ConstSymbol.ValueType  # 0
E: ConstSymbol.ValueType  # 1
EulerGamma: ConstSymbol.ValueType  # 2
Infinity: ConstSymbol.ValueType  # 3
ImaginaryUnit: ConstSymbol.ValueType  # 4
Global___ConstSymbol: _TypeAlias = ConstSymbol  # noqa: Y015

@_typing.final
class Rational(_message.Message):
    """Represents a constant, rational number."""

    DESCRIPTOR: _descriptor.Descriptor

    NUMERATOR_FIELD_NUMBER: _builtins.int
    DENOMINATOR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def numerator(self) -> Global___Parameter: ...
    @_builtins.property
    def denominator(self) -> Global___Parameter: ...
    def __init__(
        self,
        *,
        numerator: Global___Parameter | None = ...,
        denominator: Global___Parameter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["denominator", b"denominator", "numerator", b"numerator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["denominator", b"denominator", "numerator", b"numerator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Rational: _TypeAlias = Rational  # noqa: Y015

@_typing.final
class Parameter(_message.Message):
    """A single parameter of a sympy expression."""

    DESCRIPTOR: _descriptor.Descriptor

    CONST_INT_FIELD_NUMBER: _builtins.int
    SYMBOL_FIELD_NUMBER: _builtins.int
    CONST_RAT_FIELD_NUMBER: _builtins.int
    CONST_FLOAT_FIELD_NUMBER: _builtins.int
    CONST_SYMBOL_FIELD_NUMBER: _builtins.int
    const_int: _builtins.int
    symbol: _builtins.str
    const_float: _builtins.float
    const_symbol: Global___ConstSymbol.ValueType
    @_builtins.property
    def const_rat(self) -> Global___Rational: ...
    def __init__(
        self,
        *,
        const_int: _builtins.int = ...,
        symbol: _builtins.str = ...,
        const_rat: Global___Rational | None = ...,
        const_float: _builtins.float = ...,
        const_symbol: Global___ConstSymbol.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["const_float", b"const_float", "const_int", b"const_int", "const_rat", b"const_rat", "const_symbol", b"const_symbol", "parameter", b"parameter", "symbol", b"symbol"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["const_float", b"const_float", "const_int", b"const_int", "const_rat", b"const_rat", "const_symbol", b"const_symbol", "parameter", b"parameter", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_parameter: _TypeAlias = _typing.Literal["const_int", "symbol", "const_rat", "const_float", "const_symbol"]  # noqa: Y015
    _WhichOneofArgType_parameter: _TypeAlias = _typing.Literal["parameter", b"parameter"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_parameter) -> _WhichOneofReturnType_parameter | None: ...

Global___Parameter: _TypeAlias = Parameter  # noqa: Y015

@_typing.final
class Operand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TERM_FIELD_NUMBER: _builtins.int
    PARAMETER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def term(self) -> Global___Term: ...
    @_builtins.property
    def parameter(self) -> Global___Parameter: ...
    def __init__(
        self,
        *,
        term: Global___Term | None = ...,
        parameter: Global___Parameter | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["operand", b"operand", "parameter", b"parameter", "term", b"term"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operand", b"operand", "parameter", b"parameter", "term", b"term"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_operand: _TypeAlias = _typing.Literal["term", "parameter"]  # noqa: Y015
    _WhichOneofArgType_operand: _TypeAlias = _typing.Literal["operand", b"operand"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_operand) -> _WhichOneofReturnType_operand | None: ...

Global___Operand: _TypeAlias = Operand  # noqa: Y015

@_typing.final
class Term(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FUNCTION_FIELD_NUMBER: _builtins.int
    OPERANDS_FIELD_NUMBER: _builtins.int
    function: Global___Function.ValueType
    @_builtins.property
    def operands(self) -> _containers.RepeatedCompositeFieldContainer[Global___Operand]: ...
    def __init__(
        self,
        *,
        function: Global___Function.ValueType = ...,
        operands: _abc.Iterable[Global___Operand] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["function", b"function", "operands", b"operands"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Term: _TypeAlias = Term  # noqa: Y015
