# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/sympy.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bqualtran/protos/sympy.proto\x12\x08qualtran\"V\n\tParameter\x12\x13\n\tconst_int\x18\x01 \x01(\x05H\x00\x12\x10\n\x06symbol\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x63onst_irrat\x18\x03 \x01(\tH\x00\x42\x0b\n\tparameter\"^\n\x07Operand\x12\x1e\n\x04term\x18\x01 \x01(\x0b\x32\x0e.qualtran.TermH\x00\x12(\n\tparameter\x18\x02 \x01(\x0b\x32\x13.qualtran.ParameterH\x00\x42\t\n\x07operand\"Q\n\x04Term\x12$\n\x08\x66unction\x18\x01 \x01(\x0e\x32\x12.qualtran.Function\x12#\n\x08operands\x18\x02 \x03(\x0b\x32\x11.qualtran.Operand*J\n\x08\x46unction\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08\x41\x44\x44ITION\x10\x01\x12\x12\n\x0eMULTIPLICATION\x10\x02\x12\t\n\x05POWER\x10\x03\x12\x07\n\x03MOD\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.sympy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNCTION']._serialized_start=308
  _globals['_FUNCTION']._serialized_end=382
  _globals['_PARAMETER']._serialized_start=41
  _globals['_PARAMETER']._serialized_end=127
  _globals['_OPERAND']._serialized_start=129
  _globals['_OPERAND']._serialized_end=223
  _globals['_TERM']._serialized_start=225
  _globals['_TERM']._serialized_end=306
# @@protoc_insertion_point(module_scope)
