# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qualtran/protos/sympy.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bqualtran/protos/sympy.proto\x12\x08qualtran\"\\\n\x08Rational\x12&\n\tnumerator\x18\x01 \x01(\x0b\x32\x13.qualtran.Parameter\x12(\n\x0b\x64\x65nominator\x18\x02 \x01(\x0b\x32\x13.qualtran.Parameter\"\xae\x01\n\tParameter\x12\x13\n\tconst_int\x18\x01 \x01(\x05H\x00\x12\x10\n\x06symbol\x18\x02 \x01(\tH\x00\x12\'\n\tconst_rat\x18\x03 \x01(\x0b\x32\x12.qualtran.RationalH\x00\x12\x15\n\x0b\x63onst_float\x18\x04 \x01(\x02H\x00\x12-\n\x0c\x63onst_symbol\x18\x05 \x01(\x0e\x32\x15.qualtran.ConstSymbolH\x00\x42\x0b\n\tparameter\"^\n\x07Operand\x12\x1e\n\x04term\x18\x01 \x01(\x0b\x32\x0e.qualtran.TermH\x00\x12(\n\tparameter\x18\x02 \x01(\x0b\x32\x13.qualtran.ParameterH\x00\x42\t\n\x07operand\"Q\n\x04Term\x12$\n\x08\x66unction\x18\x01 \x01(\x0e\x32\x12.qualtran.Function\x12#\n\x08operands\x18\x02 \x03(\x0b\x32\x11.qualtran.Operand*\x90\x01\n\x08\x46unction\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x41\x64\x64\x10\x01\x12\x07\n\x03Mul\x10\x02\x12\x07\n\x03Pow\x10\x03\x12\x07\n\x03Mod\x10\x04\x12\x07\n\x03Log\x10\x05\x12\t\n\x05\x46loor\x10\x06\x12\x0b\n\x07\x43\x65iling\x10\x07\x12\x07\n\x03Max\x10\x08\x12\x07\n\x03Min\x10\t\x12\x07\n\x03Sin\x10\n\x12\x07\n\x03\x43os\x10\x0b\x12\x07\n\x03Tan\x10\x0c\x12\x08\n\x04Log2\x10\r*M\n\x0b\x43onstSymbol\x12\x06\n\x02Pi\x10\x00\x12\x05\n\x01\x45\x10\x01\x12\x0e\n\nEulerGamma\x10\x02\x12\x0c\n\x08Infinity\x10\x03\x12\x11\n\rImaginaryUnit\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qualtran.protos.sympy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUNCTION']._serialized_start=492
  _globals['_FUNCTION']._serialized_end=636
  _globals['_CONSTSYMBOL']._serialized_start=638
  _globals['_CONSTSYMBOL']._serialized_end=715
  _globals['_RATIONAL']._serialized_start=41
  _globals['_RATIONAL']._serialized_end=133
  _globals['_PARAMETER']._serialized_start=136
  _globals['_PARAMETER']._serialized_end=310
  _globals['_OPERAND']._serialized_start=312
  _globals['_OPERAND']._serialized_end=406
  _globals['_TERM']._serialized_start=408
  _globals['_TERM']._serialized_end=489
# @@protoc_insertion_point(module_scope)
