"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2023 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Function:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FunctionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Function.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE: _Function.ValueType  # 0
    ADDITION: _Function.ValueType  # 1
    MULTIPLICATION: _Function.ValueType  # 2
    POWER: _Function.ValueType  # 3
    MOD: _Function.ValueType  # 4

class Function(_Function, metaclass=_FunctionEnumTypeWrapper):
    """A function sympy expression."""

NONE: Function.ValueType  # 0
ADDITION: Function.ValueType  # 1
MULTIPLICATION: Function.ValueType  # 2
POWER: Function.ValueType  # 3
MOD: Function.ValueType  # 4
global___Function = Function

@typing_extensions.final
class Fraction(google.protobuf.message.Message):
    """Represents a constant, rational number."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUMERATOR_FIELD_NUMBER: builtins.int
    DENOMINATOR_FIELD_NUMBER: builtins.int
    numerator: builtins.int
    denominator: builtins.int
    def __init__(
        self,
        *,
        numerator: builtins.int = ...,
        denominator: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["denominator", b"denominator", "numerator", b"numerator"]) -> None: ...

global___Fraction = Fraction

@typing_extensions.final
class Parameter(google.protobuf.message.Message):
    """A single parameter of a sympy expression."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONST_INT_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    CONST_IRRAT_FIELD_NUMBER: builtins.int
    CONST_RAT_FIELD_NUMBER: builtins.int
    const_int: builtins.int
    symbol: builtins.str
    const_irrat: builtins.str
    @property
    def const_rat(self) -> global___Fraction: ...
    def __init__(
        self,
        *,
        const_int: builtins.int = ...,
        symbol: builtins.str = ...,
        const_irrat: builtins.str = ...,
        const_rat: global___Fraction | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["const_int", b"const_int", "const_irrat", b"const_irrat", "const_rat", b"const_rat", "parameter", b"parameter", "symbol", b"symbol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["const_int", b"const_int", "const_irrat", b"const_irrat", "const_rat", b"const_rat", "parameter", b"parameter", "symbol", b"symbol"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parameter", b"parameter"]) -> typing_extensions.Literal["const_int", "symbol", "const_irrat", "const_rat"] | None: ...

global___Parameter = Parameter

@typing_extensions.final
class Operand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TERM_FIELD_NUMBER: builtins.int
    PARAMETER_FIELD_NUMBER: builtins.int
    @property
    def term(self) -> global___Term: ...
    @property
    def parameter(self) -> global___Parameter: ...
    def __init__(
        self,
        *,
        term: global___Term | None = ...,
        parameter: global___Parameter | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["operand", b"operand", "parameter", b"parameter", "term", b"term"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operand", b"operand", "parameter", b"parameter", "term", b"term"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["operand", b"operand"]) -> typing_extensions.Literal["term", "parameter"] | None: ...

global___Operand = Operand

@typing_extensions.final
class Term(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUNCTION_FIELD_NUMBER: builtins.int
    OPERANDS_FIELD_NUMBER: builtins.int
    function: global___Function.ValueType
    @property
    def operands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Operand]: ...
    def __init__(
        self,
        *,
        function: global___Function.ValueType = ...,
        operands: collections.abc.Iterable[global___Operand] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["function", b"function", "operands", b"operands"]) -> None: ...

global___Term = Term
