#!/usr/bin/env bash

#####
# The main file to use to setup your PYTHONPATH. It sets up all cirq modules on the path.
# The file can be sourced from any location with bash or zsh.
# Usage:
#   source dev_tools/pypath
#####


if [ -n "${ZSH_VERSION}" ]; then
    # shellcheck disable=2296,2298
    _PYPATH_BASE_DIR="${${(%):-%x}:a:h:h}"
else
    _PYPATH_BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

_PYPATH_PREFIX="${_PYPATH_BASE_DIR}"

[[ $PYTHONPATH == ${_PYPATH_PREFIX}* ]] ||
    export PYTHONPATH="${_PYPATH_PREFIX}${PYTHONPATH:+:}${PYTHONPATH}"

unset _PYPATH_BASE_DIR
unset _PYPATH_PREFIX
