#!/usr/bin/env python3
"""Reproduce the cultivation spacetime volume heatmap from the FLASQ paper.

This generates the figure labeled 'cultivation_expected_cost' from
Appendix D (Section "Cultivation", specifically Cref{fig:cultivation_expected_cost}).
The figure plots the optimal expected spacetime volume of magic state
cultivation as a function of the physical error rate (x-axis) and the
target logical error rate (y-axis).

At each point in the grid, the script searches the simulation data for the
cultivation configuration (distance-3 or distance-5, and postselection
threshold) that achieves the target logical error rate at the given physical
error rate with the lowest expected spacetime volume.  White regions in the
lower-right corner indicate parameter regimes where no simulated configuration
achieves the target error rate.

The simulation data in cultivation_simulation_summary.csv was generated by
running the cultivation protocol from Gidney (2024) at many physical error
rates and postselection thresholds.  See methodology.md for full details on
how the data was produced.

Usage:
    # Display interactively:
    python plot_cultivation_figure.py

    # Save to file:
    python plot_cultivation_figure.py -o cultivation_expected_cost.png

    # Quick preview at lower resolution (50x50 grid, ~5s vs ~3min):
    python plot_cultivation_figure.py --grid-res 50 -o preview.png
"""

import argparse
import pathlib
from typing import Optional

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_and_filter(csv_path: pathlib.Path) -> pd.DataFrame:
    """Load the cultivation simulation summary and apply standard filters.

    The filters match those used when generating the published figure:

    - errors >= 0: exclude any rows where the confidence interval
      construction failed (negative sentinel).
    - expected_block_cost_at_d_15 <= 100: exclude configurations so
      expensive that they would never be chosen by the optimizer.
      The block cost is the expected volume divided by the volume of a
      single distance-15 logical block (2 * (15+1)^2 * 15 = 7680
      qubit-rounds), giving a dimensionless cost in "logical blocks."
    - low_10 > 0: exclude rows where the lower 10% confidence bound on
      the logical error rate is zero, indicating insufficient statistics.
    - error_rate <= 2.1e-3: restrict to physical error rates at or below
      the surface code threshold region.  This removes the very high
      error-rate data points that are not useful for the FLASQ model.
    """
    df = pd.read_csv(csv_path)

    # The CSV may have a spurious index column from pandas serialization.
    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])

    # Compute the block cost used for filtering.  A distance-15 logical
    # block has volume 2 * (d+1)^2 * d = 2 * 16^2 * 15 = 7680 qubit-rounds.
    df["expected_block_cost_at_d_15"] = df["expected_volume"] / (2 * (15 + 1) ** 2 * 15)

    filtered = df[df["errors"] >= 0].copy()
    filtered = filtered[filtered["expected_block_cost_at_d_15"] <= 100]
    filtered = filtered[filtered["low_10"] > 0]
    filtered = filtered[filtered["error_rate"] <= 2.1e-3]

    return filtered


# ---------------------------------------------------------------------------
# Search: find the optimal cultivation configuration for given constraints
# ---------------------------------------------------------------------------


def search_dataframe(
    df: pd.DataFrame, physical_error_rate: float, target_logical_error_rate: float
) -> Optional[pd.DataFrame]:
    """Find the row minimizing expected_volume for given error constraints.

    The lookup mirrors the "round up and round down" policy described in
    the paper's figure caption: we round the physical error rate *up* to
    the nearest simulated value (so that we overestimate noise) and then
    require that the best-estimate logical error rate is at or below the
    target (so that we do not underestimate the cultivation error).

    Among all rows satisfying both constraints (across both cultivation
    distances d=3 and d=5), the one with minimum expected_volume is returned.

    Returns None if no configuration satisfies the constraints.
    """
    if df.empty:
        return None

    # Find the smallest simulated error_rate >= physical_error_rate.
    fp_tol = 1e-9
    unique_rates = sorted(df["error_rate"].unique())

    actual_rate = None
    for rate in unique_rates:
        if rate >= physical_error_rate - fp_tol:
            actual_rate = rate
            break

    if actual_rate is None:
        return None

    rate_df = df[np.isclose(df["error_rate"], actual_rate, rtol=0, atol=fp_tol)]
    if rate_df.empty:
        return None

    # Filter to configurations achieving the target logical error rate.
    # "best_estimate" is the maximum-likelihood estimate of the T-gate
    # logical error rate (= 2x the simulated S|+> error rate).
    satisfying = rate_df[rate_df["best_estimate"] <= target_logical_error_rate]
    if satisfying.empty:
        return None

    return satisfying.sort_values("expected_volume").head(1)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _log_edges(points: np.ndarray) -> np.ndarray:
    """Compute cell boundary edges for pcolormesh from log-spaced centers.

    pcolormesh requires cell *edges* (N+1 values for N cells).  We place
    each edge at the geometric mean of adjacent center points, with the
    outer edges extrapolated by half a log-step.
    """
    if len(points) == 1:
        f = 1.5
        return np.array([points[0] / f, points[0] * f])
    lp = np.log(points)
    mid = (lp[:-1] + lp[1:]) / 2.0
    first = lp[0] - (lp[1] - lp[0]) / 2.0
    last = lp[-1] + (lp[-1] - lp[-2]) / 2.0
    return np.exp(np.concatenate(([first], mid, [last])))


def _configure_axes(ax: plt.Axes) -> None:
    """Apply the tick and grid formatting used in the published figure.

    X-axis ticks are placed at the specific physical error rates used in
    the paper (powers-of-2 spacing from 1.25e-4 to 4e-3).  Y-axis ticks
    are at powers of 10.
    """
    x_ticks = sorted([4e-3, 2e-3, 1e-3, 5e-4, 2.5e-4, 1.25e-4])
    ax.xaxis.set_major_locator(mticker.FixedLocator(x_ticks))
    ax.xaxis.set_major_formatter(mticker.FixedFormatter([f"{v:.2e}" for v in x_ticks]))
    ax.xaxis.set_minor_locator(mticker.NullLocator())

    ax.yaxis.set_major_locator(mticker.LogLocator(base=10.0, subs=(1.0,)))
    ax.yaxis.set_major_formatter(mticker.LogFormatterSciNotation(base=10.0))
    ax.yaxis.set_minor_locator(mticker.NullLocator())

    ax.grid(True, which="major", axis="x", ls=":", lw=0.7, alpha=0.7)
    ax.grid(True, which="major", axis="y", ls=":", lw=0.5, alpha=0.7)
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")


# ---------------------------------------------------------------------------
# The figure
# ---------------------------------------------------------------------------


def plot_cultivation_heatmap(
    filtered_df: pd.DataFrame, output_path: Optional[pathlib.Path] = None, grid_res: int = 400
) -> None:
    """Generate the paper's cultivation spacetime volume heatmap.

    Constructs a grid_res x grid_res grid over:
      - x: physical error rate in [1.25e-4, 2e-3]  (log-spaced)
      - y: target logical error rate in [1e-9, 1e-4]  (log-spaced)

    For each grid point, search_dataframe finds the cultivation
    configuration minimizing expected spacetime volume (in physical
    qubit-rounds), considering both distance-3 and distance-5 protocols.
    The result is rendered as a pcolormesh heatmap with a log-scale
    colorbar.

    Args:
        filtered_df: Pre-filtered simulation data from load_and_filter.
        output_path: If provided, save the figure here.  Otherwise show
            interactively via plt.show().
        grid_res: Number of grid points per axis.  400 matches the
            published figure; 50 gives a fast preview.
    """
    # Define the evaluation grid (log-spaced on both axes).
    x_pts = np.logspace(np.log10(1.25e-4), np.log10(2e-3), num=grid_res)
    y_pts = np.sort(np.logspace(np.log10(1e-9), np.log10(1e-4), num=grid_res))

    # For each grid point, find the optimal expected volume.
    # NaN indicates no configuration achieves the target error rate
    # (rendered as white in the plot).
    color_matrix = np.full((len(y_pts), len(x_pts)), np.nan)

    print(f"Computing optimal volumes on {grid_res}×{grid_res} grid...")
    for j, log_err in enumerate(y_pts):
        for i, phys_err in enumerate(x_pts):
            result = search_dataframe(filtered_df, phys_err, log_err)
            if result is not None and not result.empty:
                color_matrix[j, i] = result.iloc[0]["expected_volume"]
    print("Done.")

    # Build the mesh edges for pcolormesh (N+1 edges for N cells).
    x_edges = _log_edges(x_pts)
    y_edges = _log_edges(y_pts)

    fig, ax = plt.subplots(figsize=(12, 10))

    # Set up log-scale color normalization from the data range.
    flat = color_matrix.flatten()
    pos = flat[~np.isnan(flat) & (flat > 0)]
    norm = None
    if pos.size > 0 and pos.min() > 0 and pos.max() > pos.min():
        norm = mcolors.LogNorm(vmin=pos.min(), vmax=pos.max())

    mesh = ax.pcolormesh(x_edges, y_edges, color_matrix, norm=norm, cmap="viridis", shading="flat")

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Physical Error Rate")
    ax.set_ylabel("Target Logical Error Rate")
    ax.set_title("Optimal Cultivation Spacetime Volume")

    _configure_axes(ax)

    if mesh:
        cbar = fig.colorbar(mesh, ax=ax)
        cbar.set_label("Expected Volume (Qubit·Rounds)")

    plt.tight_layout()
    if output_path:
        fig.savefig(output_path, dpi=150, bbox_inches="tight")
        print(f"Saved: {output_path}")
    else:
        plt.show()
    plt.close(fig)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "-i",
        "--input",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent / "cultivation_simulation_summary.csv",
        help="Path to cultivation simulation CSV (default: co-located CSV)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=pathlib.Path,
        default=None,
        help="Output image path (default: display interactively)",
    )
    parser.add_argument(
        "--grid-res",
        type=int,
        default=400,
        help="Grid resolution per axis (default: 400 to match paper, use 50 for fast preview)",
    )
    args = parser.parse_args()

    if not args.input.exists():
        parser.error(f"Input not found: {args.input}")

    print(f"Loading: {args.input}")
    filtered = load_and_filter(args.input)
    print(f"Filtered: {len(filtered)} rows")

    plot_cultivation_heatmap(filtered, args.output, args.grid_res)


if __name__ == "__main__":
    main()
