#  Copyright 2024 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import math

import cirq
import numpy as np
import pytest
from frozendict import frozendict

from qualtran.resource_counting import get_cost_value, QubitCount
from qualtran.surface_code.flasq.cirq_interop import convert_circuit_for_flasq_analysis
from qualtran.surface_code.flasq.examples.hwp import build_hwp_circuit, build_parallel_rz_circuit
from qualtran.surface_code.flasq.flasq_model import (
    apply_flasq_cost_model,
    conservative_FLASQ_costs,
    get_rotation_depth,
)
from qualtran.surface_code.flasq.measurement_depth import TotalMeasurementDepth
from qualtran.surface_code.flasq.naive_grid_qubit_manager import NaiveGridQubitManager
from qualtran.surface_code.flasq.span_counting import TotalSpanCost
from qualtran.surface_code.flasq.symbols import ROTATION_ERROR, T_REACT, V_CULT_FACTOR
from qualtran.surface_code.flasq.volume_counting import FLASQGateTotals


def _hamming_weight(n):
    return bin(n).count("1")


@pytest.mark.slow
def test_build_hwp_circuit():
    n_qubits_data = 7
    angle = 0.123

    _, circuit, data_qubits = build_hwp_circuit(n_qubits_data=n_qubits_data, angle=angle)

    assert len(circuit) > 0
    assert len(data_qubits) == n_qubits_data

    # Check qubit locations
    for q in data_qubits:
        assert q.row >= 0


@pytest.mark.slow
def test_convert_hwp_circuit_for_flasq():
    n_qubits_data = 7
    angle = 0.123

    # 1. Setup managers that the test can inspect.
    data_qubit_manager = NaiveGridQubitManager(max_cols=10, negative=False)
    ancilla_qubit_manager = NaiveGridQubitManager(max_cols=10, negative=True)

    # 1. Build the initial circuit
    hwp_bloq, circuit, data_qubits = build_hwp_circuit(
        n_qubits_data=n_qubits_data,
        angle=angle,
        data_qubit_manager=data_qubit_manager,
        ancilla_qubit_manager=ancilla_qubit_manager,
    )

    # 2. Convert it for FLASQ analysis
    in_quregs = {"x": np.asarray(data_qubits)}
    cbloq, decomposed_circuit = convert_circuit_for_flasq_analysis(
        circuit,
        signature=hwp_bloq.signature,
        qubit_manager=ancilla_qubit_manager,
        in_quregs=in_quregs,
        out_quregs=in_quregs,
    )

    # 3. Verify the conversion
    assert cbloq is not None
    assert decomposed_circuit is not None
    assert len(decomposed_circuit) > 0

    # Check that the expected number of ancillas were allocated during decomposition.
    n_ancilla_hwc = n_qubits_data - _hamming_weight(n_qubits_data)
    n_ancilla_out = math.ceil(math.log2(n_qubits_data + 1))
    expected_ancillas = n_ancilla_hwc + n_ancilla_out

    # Check the number of ancillas generated by the manager. We use
    # `num_generated_qubits` because the ancillas are temporary and will be
    # deallocated by the end of the circuit, so `all_qubits()` would be empty.
    assert ancilla_qubit_manager.num_generated_qubits == expected_ancillas

    # Verify all qubits in the decomposed circuit are accounted for.
    ancillas_in_circuit = set(decomposed_circuit.all_qubits()) - set(data_qubits)
    assert len(ancillas_in_circuit) == expected_ancillas


def test_build_parallel_rz_circuit():
    """Lightly test the parallel Rz circuit builder."""
    n_qubits_data = 16
    angle = 0.456

    circuit, data_qubits = build_parallel_rz_circuit(n_qubits_data=n_qubits_data, angle=angle)

    assert len(data_qubits) == n_qubits_data
    assert len(circuit) == 1  # Should be a single moment
    moment = circuit[0]
    assert len(moment.operations) == n_qubits_data
    for op in moment.operations:
        assert isinstance(op.gate, cirq.ops.common_gates.ZPowGate)
        # cirq.rz(rads) is a ZPowGate with exponent = rads / pi
        assert op.gate.exponent == angle / np.pi


@pytest.mark.slow
def test_hwp_vs_parallel_rz_spacetime_volume():
    """Integration test to verify spacetime volume comparison.

    This test replicates the example from the hwp_notebook and asserts that
    the parallel Rz method should have a smaller spacetime volume, capturing
    a bug where it was counter-intuitively larger. It also verifies that
    both methods are in the volume-limited regime for these parameters.
    """
    # --- 1. Define Parameters from Notebook Example ---
    n_qubits_data = 7
    angle = 0.123
    n_total_logical_qubits = 25
    rotation_error = 1e-7
    cost_model = conservative_FLASQ_costs
    logical_timesteps_per_measurement = 0.5
    vcult_factor = 6.0

    assumptions = frozendict(
        {ROTATION_ERROR: rotation_error, V_CULT_FACTOR: vcult_factor, T_REACT: 1.0}
    )

    # --- 2. Analyze Method 1: Hamming Weight Phasing ---
    data_qubit_manager_hwp = NaiveGridQubitManager(max_cols=10, negative=False)
    ancilla_qubit_manager_hwp = NaiveGridQubitManager(max_cols=10, negative=True)
    hwp_bloq, hwp_circuit, hwp_data_qubits = build_hwp_circuit(
        n_qubits_data=n_qubits_data,
        angle=angle,
        data_qubit_manager=data_qubit_manager_hwp,
        ancilla_qubit_manager=ancilla_qubit_manager_hwp,
    )
    in_quregs_hwp = {"x": np.asarray(hwp_data_qubits)}
    hwp_cbloq, _ = convert_circuit_for_flasq_analysis(
        hwp_circuit,
        signature=hwp_bloq.signature,
        qubit_manager=ancilla_qubit_manager_hwp,
        in_quregs=in_quregs_hwp,
        out_quregs=in_quregs_hwp,
    )
    hwp_counts = get_cost_value(hwp_cbloq, FLASQGateTotals())
    hwp_span = get_cost_value(hwp_cbloq, TotalSpanCost())
    hwp_depth = get_cost_value(
        hwp_cbloq, TotalMeasurementDepth(rotation_depth=get_rotation_depth(rotation_error))
    )
    hwp_qubit_counts = get_cost_value(hwp_cbloq, QubitCount())
    # Qualtran's QubitCount calculates peak simultaneous usage (12),
    # which is lower than the naive total unique count (14 = 7 data + 7 ancilla)
    # because some ancillas are freed before the peak is reached.
    assert hwp_qubit_counts == 12
    hwp_summary_symbolic = apply_flasq_cost_model(
        cost_model,
        n_total_logical_qubits,
        hwp_qubit_counts,
        hwp_counts,
        hwp_span,
        hwp_depth,
        logical_timesteps_per_measurement=logical_timesteps_per_measurement,
    )
    hwp_summary = hwp_summary_symbolic.resolve_symbols(assumptions=assumptions)

    # --- 3. Analyze Method 2: Parallel Rz ---
    parallel_rz_circuit, _ = build_parallel_rz_circuit(n_qubits_data=n_qubits_data, angle=angle)
    parallel_rz_cbloq, _ = convert_circuit_for_flasq_analysis(parallel_rz_circuit)
    parallel_rz_counts = get_cost_value(parallel_rz_cbloq, FLASQGateTotals())
    parallel_rz_span = get_cost_value(parallel_rz_cbloq, TotalSpanCost())
    parallel_rz_depth = get_cost_value(
        parallel_rz_cbloq, TotalMeasurementDepth(rotation_depth=get_rotation_depth(rotation_error))
    )
    rz_qubit_counts = get_cost_value(parallel_rz_cbloq, QubitCount())
    assert rz_qubit_counts == 7
    parallel_rz_summary_symbolic = apply_flasq_cost_model(
        cost_model,
        n_total_logical_qubits,
        rz_qubit_counts,
        parallel_rz_counts,
        parallel_rz_span,
        parallel_rz_depth,
        logical_timesteps_per_measurement=logical_timesteps_per_measurement,
    )
    parallel_rz_summary = parallel_rz_summary_symbolic.resolve_symbols(assumptions=assumptions)

    # --- 4. Assertions ---
    assert hwp_summary.is_volume_limited
    assert parallel_rz_summary.is_volume_limited
    assert parallel_rz_summary.total_spacetime_volume < hwp_summary.total_spacetime_volume


@pytest.mark.slow
@pytest.mark.parametrize("n_qubits_data", [4, 7, 8, 15, 16, 31, 42])
def test_hwp_qubit_count_logic(n_qubits_data):
    """Tests the logic for qubit counting in HammingWeightPhasing.

    This test compares a manual calculation of the total number of unique qubits
    used in the HWP decomposition against the `QubitCount` cost metric from
    Qualtran, which calculates the peak simultaneous qubit usage.

    This test is expected to fail for some values, highlighting the difference
    between these two quantities.
    """
    # 1. Manual calculation of total unique qubits expected to be used.
    expected_total_unique_qubits = (
        n_qubits_data
        + (n_qubits_data - _hamming_weight(n_qubits_data))
        + math.ceil(math.log2(n_qubits_data + 1))
    )

    # 2. Build the circuit and the corresponding CompositeBloq.
    ancilla_qubit_manager = NaiveGridQubitManager(max_cols=20, negative=True)
    hwp_bloq, hwp_circuit, hwp_data_qubits = build_hwp_circuit(
        n_qubits_data=n_qubits_data,
        angle=0.123,  # Angle does not affect qubit count.
        ancilla_qubit_manager=ancilla_qubit_manager,
    )
    in_quregs = {"x": np.asarray(hwp_data_qubits)}
    hwp_cbloq, _ = convert_circuit_for_flasq_analysis(
        hwp_circuit,
        signature=hwp_bloq.signature,
        qubit_manager=ancilla_qubit_manager,
        in_quregs=in_quregs,
        out_quregs=in_quregs,
    )

    # 3. Get the peak qubit count from the CompositeBloq.
    actual_peak_qubit_count = get_cost_value(hwp_cbloq, QubitCount())

    # 4. Assert against expected peak simultaneous qubit counts.
    # Qualtran's QubitCount calculates peak simultaneous usage, which differs
    # from the manual calculation of total unique qubits for some values.
    expected_peak_counts = {4: 10, 7: 12, 8: 19, 15: 27, 16: 36, 31: 58, 42: 85}
    assert actual_peak_qubit_count == expected_peak_counts[n_qubits_data]
